### ISSUE TITLE
HGD dataset loading with new braindecode

### ISSUE THREAD

**Issue by bkozyrskiy** [robintibor/high-gamma-dataset#2]
The last version of braindecode doesn't contain functions used in this repository. How to load a high gamma dataset with the current version of braindecode?

**Comment by moritz-gerster** [comment]
I have the same problem!

**Comment by robintibor** [comment]
For code that reproduced HBM 2017 results with current braindecode see https://gist.github.com/robintibor/6a95a85088e651392c1bb4f912d1528e

**Comment by moritz-gerster** [comment]
> For code that reproduced HBM 2017 results with current braindecode see https://gist.github.com/robintibor/6a95a85088e651392c1bb4f912d1528e

Thank you! However, I get the error message 
"ModuleNotFoundError: No module named 'hyperoptim'"

**Comment by robintibor** [comment]
Yeah don't run the first file, it is just for my own experiment system, and you can see good hyperparameters inside ... you can call the `run_exp` function directly in the second file ( https://gist.github.com/robintibor/6a95a85088e651392c1bb4f912d1528e#file-run_and_train_amp_grad-py ) from the outside... as said appropriate parameter values can just be copied from first file
