### ISSUE TITLE
cannot open the file to download dataset

### ISSUE THREAD

**Issue by shijian97** [robintibor/high-gamma-dataset#5]
[Errno 2] Unable to open file (unable to open file: name = './test/1.mat', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by shijian97** [comment]
hello, thanks for your great job! but when I download the high-gamma file using
```
cnt = BBCIDataset('./test/1.mat').load()
```
there a mistake happens with "Unable to open file (unable to open file: name = './test/1.mat', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)"
can you help me ?

**Comment by RazMagal** [comment]
Have you solved the issue?
